### PR TITLE
Create 1155079068.md

### PR DESCRIPTION
**Pull request by slcssamy**

### CODE REVIEW

**Comment by HoTszYanAnn** [comment]
Is there anyone hasn't fulfilled the requirement of doing two reviews? Please done quickly! As the deadline is before tonight, I am scared that this request cannot be done before 12:00. I will approve this review after 1145 if it is still no one approved. :P

**Comment by HoTszYanAnn** [comment]
That's great!

**Comment by HoTszYanAnn** [comment]
@slcssamy Please insert your name card in the README.md as soon as possible :)

**Comment by slcssamy** [comment]
Added

「HoTszYanAnn <notifications@github.com>」在 2019年4月24日 週三，下午11:24 寫道：

**Comment by slcssamy** [comment]
What about task 3?


「Ng Wai Lam <slcssamy@gmail.com>」在 2019年4月24日 週三，下午11:26 寫道：

**Comment by HoTszYanAnn** [comment]
what is the mean of Task 3? If you mean the group task, all are finished. Also, I cannot find your name inserted in README.md.

**Comment by HoTszYanAnn** [comment]
Moreover, I find that it seems that you haven't joined this team h group. Please remember do this :)

**Comment by slcssamy** [comment]
Emm i think i have already inserted ...

「HoTszYanAnn <notifications@github.com>」在 2019年4月24日 週三，下午11:32 寫道：

**Comment by slcssamy** [comment]
How can i join the group?

「HoTszYanAnn <notifications@github.com>」在 2019年4月24日 週三，下午11:33 寫道：

**Comment by HoTszYanAnn** [comment]
https://github.com/orgs/csci3250-2019/teams/team-h/members
Can you join in with this link? or you can find in the email sent by the professor.

**Comment by HoTszYanAnn** [comment]
Capture
But here are no your sid shown :(

**Comment by HoTszYanAnn** [comment]
After joining in team h, please remember to create a new name card at project board to introduce yourself and put it in the done list. :)

**Comment by slcssamy** [comment]
I have added into the group but idk how to create a new name card...

「HoTszYanAnn <notifications@github.com>」在 2019年4月24日 週三，下午11:38 寫道：

**Comment by HoTszYanAnn** [comment]
go to the project page, click the team h project board and there will have a button to create a new card.

**Pull request merged**
