### PR TITLE
Create 1155074616.md

### PR DESCRIPTION
**Pull request by linusyukwong**
Create 1155074616.md

### CODE REVIEW

**Comment by HoTszYanAnn** [comment]
I think that your format is wrong. You should write “(your full name ) @(username in github)"

**Comment by linusyukwong** [comment]
I have updated to the correct format

**Comment by HoTszYanAnn** [comment]
I think that the sid is not needed

**Comment by linusyukwong** [comment]
Yes, I have deleted sid.

**Pull request merged**
