### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slcssamy**

### CODE REVIEW

**Comment by HoTszYanAnn** [comment]
Is there anyone haven't fulfilled the requirement? Please check and close it as soon as possible. :(

**Comment by HoTszYanAnn** [comment]
Maybe I need to approve it if it is still waiting after 1155 :(

**Comment by Abdalla981** [comment]
He has to change the format

**Comment by Abdalla981** [comment]
last line is not formatted correctly

**Comment by HoTszYanAnn** [comment]
@slcssamy Please change it quickly!!! :(

**Comment by Abdalla981** [comment]
I did update it

**Comment by HoTszYanAnn** [comment]
but I can't do review anymore :(

**Comment by Abdalla981** [comment]
I did do it

**Comment by HoTszYanAnn** [comment]
that's great!!!!!!

**Pull request merged**
